
// Save infomation user
export const USER_KEY = 'USER_KEY';

/**
 * Users
 */
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = "SIGNUP_FAIL";

export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_REQUEST = 'SIGNIN_REQUEST';
export const SIGNIN_FAIL = 'SIGNIN_FAIL';

export const GET_TOKEN = 'GET_TOKEN';
export const GET_TOKEN_SUCCESS = 'GET_TOKEN_SUCCESS';
export const GET_TOKEN_FAILED = 'GET_TOKEN_FAILED';

/**
 * Get locations
 */
export const GET_LIST_LOCATION = 'GET_LIST_LOCATION';
export const GET_LIST_LOCATION_SUCCESS = 'GET_LIST_LOCATION_SUCCESS';
export const GET_LIST_LOCATION_FAILED = 'GET_LIST_LOCATION_FAILED';
export const RESET_LOCATION_STATUS = 'RESET_LOCATION_STATUS';

/**
 * Get DataHome
 */

export const GET_BANNER = 'GET_BANNER';
export const GET_BANNER_SUCCESS = 'GET_BANNER_SUCCESS';
export const GET_BANNER_FAILED = 'GET_BANNER_FAILED';

export const GET_NEW_PRODUCT = 'GET_NEW_PRODUCT';
export const GET_NEW_PRODUCT_SUCCESS = 'GET_NEW_PRODUCT_SUCCESS';
export const GET_NEW_PRODUCT_FAILED = 'GET_NEW_PRODUCT_FAILED';
